### ISSUE TITLE
Mod Private can support compatibility any more

### ISSUE THREAD

**Issue by xanthian** [dmcpacks/Dirtmonds-Fabric#3]
Looks like the mod has been made private on CF.
Can no longer compile my mod to provide support for it correctly.

A problem occurred configuring root project 'expert_weapons'.
> Could not download dirtmonds-559519-3872332.jar (curse.maven:dirtmonds-559519:3872332)
   > Could not get resource 'https://cursemaven.com/curse/maven/dirtmonds-559519/3872332/dirtmonds-559519-3872332.jar'.
      > Could not GET 'https://cursemaven.com/curse/maven/dirtmonds-559519/3872332/dirtmonds-559519-3872332.jar'. Received status code 403 from server: Forbidden

Obviously cannot make you remove the private, but hopefully ask you to reconsider.

**Comment by dmcpacks** [comment]
The issue seemed to be on curseforges side.
